### ISSUE TITLE
Persist Fasten Database using volume mount

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [fastenhealth/fasten-onprem#237]
Have the option to store the data persistently by mapping it in the volume section in docker.

```
  Fasten:
    image: ghcr.io/fastenhealth/fasten-onprem:main
    container_name: Fasten
    environment:
      - TZ=America/Chicago
    volumes:
      - /volume1/docker/Fasten:/opt/fasten
    ports:
      - 8080:8080
    restart: unless-stopped
```
